### ISSUE TITLE
Can you use socket.on and socket.emit?

### ISSUE THREAD

**Issue by gabrieldlazcano** [mfrachet/use-socketio#13]
Any way of using those socket io functions?

**Comment by mfrachet** [comment]
In the following snippet:

```javascript
const socket = useSocket("tweet", newTweet =>
    setTweet([newTweet, ...tweets])
  );
```

`socket` is the actual socket.io socket so you can play with `socket.emit`.

Moreover, the first argument of `useSocket` is the event name you can listen to, just like if you would have done `socket.on('tweet')` 😊 

Hope this help :D
