### ISSUE TITLE
Feature Request: Provide a way to manually unsubscribe

### ISSUE THREAD

**Issue by iagobruno** [mfrachet/use-socketio#16]
**Current behavior:**

Currently, the only way to unsubscribe from an event is unmount the component.

**Proposal:**

Return a function from `useSocket` hook that, when called, cancels the subscription. Example:

```jsx
import { useSocket } from 'use-socketio'

function Component(props) {
  const { unsubscribe } = useSocket('tweet', (newTweet) => {
    // ...
  })

  return <button onClick={unsubscribe}>Stop showing tweets</button>
}
```

In this draft, I suggested that the hook return an object to be similar to the new hook described in #15 but this will be a breaking change.

**Use case examples:**
 
- User has logged out but the component can still be mounted without receiving new updates.
- A modal dialog has entered in front of the component and you don't want to receive new events because user is not paying attention anymore.
- User explicitly demonstrated that he doesn't want to receive new updates.

**Comment by iagobruno** [comment]
If you approve this idea, I will make the pull request with the implementation.

**Comment by mfrachet** [comment]
Huge move on the typescript branch and taking subscribe / unsubscribe capabilities 😊

**Comment by mfrachet** [comment]
I'm closing this, it's on master and published under the v2 of the lib 😊 .Don't hesitate to reopen if needed!
