### ISSUE TITLE
Library broken by 2.0.2 update

### ISSUE THREAD

**Issue by Mause** [mfrachet/use-socketio#36]
The library can no longer be imported, see here: https://runkit.com/embed/99svuse43itd

**Comment by mfrachet** [comment]
Oh dang, sorry about that! I'll take care of this

**Comment by mfrachet** [comment]
It should be fixed in 2.0.3, 🙏 let me know if you're still in troudble

**Comment by Mause** [comment]
Looks good, thankyou :)
