### ISSUE TITLE
sse-server a bug

### ISSUE THREAD

**Issue by ZhengXingchi** [mfrachet/use-socketio#37]
in your sse-server.js  line9
setTimeout is not very fit here, I suggest you shold use setInterval

your old code
```
  setTimeout(() => {
    const secondData = { name: "Laetitia" };

    res.write(`data: ${JSON.stringify(secondData)}`);
    res.write("\n\n");
  }, 500);
```

i suggest
```
  setInterval(() => {
    const secondData = { name: "Laetitia" };

    res.write(`data: ${JSON.stringify(secondData)}`);
    res.write("\n\n");
  }, 500);
```

**Comment by mfrachet** [comment]
Hello :) .

SSE is still in draft, but thanks for reporting :). Can you tell me what is the problem when using setTimeout? The idea was just to defer the message sending to create a "more real case" by simulating some network latency 😊

**Comment by ZhengXingchi** [comment]
you see.when you use `setTimeout` api to create one more data.then the browser will fail to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING.because the serve  is  not close completely.

**Comment by mfrachet** [comment]
Are you interested in making a PR to fix this or do you prefer I take it? 😊

**Comment by ZhengXingchi** [comment]
sorry&nbsp;to&nbsp;see&nbsp;&nbsp;your&nbsp;&nbsp;answer&nbsp;&nbsp;&nbsp;so&nbsp;&nbsp;late。i&nbsp;&nbsp;will&nbsp;&nbsp;make&nbsp;&nbsp;a&nbsp;&nbsp;PR&nbsp;&nbsp;tomorrow&nbsp;&nbsp;to&nbsp;&nbsp;fix&nbsp;&nbsp;this&nbsp;&nbsp;if&nbsp;&nbsp;that&nbsp;&nbsp;is&nbsp;&nbsp;convenient。


---Original---

**Comment by ZhengXingchi** [comment]
sorry to see  your  answer   so  late。i  will  make  a  PR  tomorrow  to  fix  this  if  that  is  convenient。😃

**Comment by ZhengXingchi** [comment]
the travis Ci failed to run because you take a  minor mistake.you should update your config in order to run perfectly.
```
{
  "language": "node_js",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "node_js": [
    "10"
  ],
  "addons": {
    "apt": {
      "packages": [
        "libgconf-2-4"
      ]
    }
  },
  "cache": {
    "npm": true,
    "directories": [
      "~/.cache"
    ]
  },
  "before_script": [
    "yarn check:lint"
  ],
  "script": [
    "npm run build",
    "npm start",
    "npm run start:test-server",
    "npm run e2e:ci",
    "kill $(jobs -p) || true"
  ]
}
```
