### ISSUE TITLE
Change return values

### ISSUE THREAD

**Issue by parweb** [mfrachet/use-socketio#5]
https://github.com/mfrachet/use-socketio/blob/73601fec48506de4eada21f6f3bdb1aef92122cf/src/useSocket.js#L11

Could be ? (check https://github.com/parweb/use-socketio/pulls?q=is%3Apr+is%3Aclosed)
`
return [value, (message) => socket.emit(eventKey, message), socket];
`

**Comment by mfrachet** [comment]
It absolutely could 😊 You can pr on this if you'd like to 😄

**Comment by mfrachet** [comment]
Since the v1.0.0 has been published, it's not possible to rely on a callback to avoid unecessary state modifications
