### ISSUE TITLE
You are using `useEffect` in a wrong way

### ISSUE THREAD

**Issue by jantimon** [mfrachet/use-socketio#9]
Hey,

I was curious how your hook works and saw that you are using `useEffect` in a very inefficient way:

https://github.com/mfrachet/use-socketio/blob/52dc91b93ff6d4a73e11583fd439d0c2e56037a9/src/useSocket.js#L7-L13

Use effect has two parameters - the callback and the reasons to execute the effect again.  
As you didn't specify any reasons it will execute the effect **on every** render of the component which is using your hook.

See https://reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects for details.

So your code could be improved like this:

```js
const callbackRef = useRef(callback);
callbackRef.current = callback;

useEffect(() => {
    if (eventKey) {
      function socketHandler() {
         callbackRef.current && callbackRef.current.apply(this, arguments);
      }
      socket.on(eventKey, socketHandler);
      return () => socket.removeListener(eventKey, socketHandler);
    }
}, ['eventKey']);
```

That way `socket.on` and `socket.removeListener` are only called if the components `mounts`/`unmounts` or `eventKey` changes

**Comment by mfrachet** [comment]
Thanks for having pointing this out! I'm looking to study :blush:

I'm having a question concerning the `useRef` you've proposed.

I'm not sure to understand why we have to re-affect the `current` prop of the `callbackRef` in:

```javascript
const callbackRef = useRef(callback);
callbackRef.current = callback;
```

?

**Comment by jantimon** [comment]
Every time you run the following code it will create a "new" instance of the function:

```js
(newTweet) =>
  setTweet([newTweet, ...tweets])
)
```

So if we `useEffect(() => {}, [callback])` it would invalidate the cache on every run.

To get around this we don't add it to the `useEffect` array.  

But unfortunately this leads us to a situation that `useEffect` will cache the callback and it might become outdated.

So we use a reference to the latest callback that can be used inside `useEffect`.

**Comment by mfrachet** [comment]
Oh I got it!

Thanks for taking time to explains this 😄  . I'm closing this for now and have merged the code you've proposed 😊 

Again, thank you for this 👍
